CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_projects_owner ON projects(owner_id);
CREATE INDEX IF NOT EXISTS idx_projects_invite ON projects(invite_code);
CREATE INDEX IF NOT EXISTS idx_members_project ON project_members(project_id);
CREATE INDEX IF NOT EXISTS idx_members_user ON project_members(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_project ON messages(project_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_relayed ON messages(relayed_msg_id);
CREATE INDEX IF NOT EXISTS idx_messages_created ON messages(created_at);
CREATE INDEX IF NOT EXISTS idx_files_project ON files(project_id);
CREATE INDEX IF NOT EXISTS idx_files_category ON files(project_id, category);
CREATE INDEX IF NOT EXISTS idx_invoices_project ON invoices(project_id);
CREATE INDEX IF NOT EXISTS idx_invoices_stripe ON invoices(stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_glossary_jobs_project ON glossary_jobs(project_id);
CREATE INDEX IF NOT EXISTS idx_glossary_terms_project ON glossary_terms(project_id);
CREATE INDEX IF NOT EXISTS idx_glossary_terms_approved ON glossary_terms(project_id, is_approved);
CREATE INDEX IF NOT EXISTS idx_content_hashes ON content_hashes(sha256_hash);
CREATE INDEX IF NOT EXISTS idx_chatbot_cache ON chatbot_cache(question_hash);
CREATE INDEX IF NOT EXISTS idx_user_states ON user_states(current_state);
